services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=database_user
      - POSTGRES_PASSWORD=database_pass
    ports:
      - "5510:5432"
    volumes:
      - database:/var/lib/postgresql/data

networks:
  default:
    driver: bridge

volumes:
  database:
    driver: local